<?php
require __DIR__ . '/../vendor/autoload.php';


$xml = "<?xml version=\"1.0\" encoding=\"UTF-8\" ?><serverresponse id='4.101'><code>get_league_list_All</code><status>success</status><ts>1671895029361</ts><gtype>FT</gtype><datelist><date_0><month>十二月</month><date>24</date><week>星期六</week></date_0><date_1><month>十二月</month><date>25</date><week>星期日</week></date_1><date_2><month>十二月</month><date>26</date><week>星期一</week></date_2><date_3><month>十二月</month><date>27</date><week>星期二</week></date_3><date_4><month>十二月</month><date>28</date><week>星期三</week></date_4><date_5><month>十二月</month><date>29</date><week>星期四</week></date_5><date_6><month>十二月</month><date>30</date><week>星期五</week></date_6><date_7><month>十二月</month><date>31</date><week>星期六</week></date_7></datelist><coupons><coupon_sw>Y</coupon_sw><coupon id='1'><name>今日赛事</name><lid>102744,100123,101743,101322,103231,101323,108688</lid><field>cp1</field></coupon><coupon id='2'><name>非洲和中东的顶级赛事</name><lid>102744,101322,103231,101323</lid><field>HotGame_FT_lid_6</field></coupon></coupons><classifier><classifier_sw>Y</classifier_sw><region name='阿尔及利亚' id='29' t_sort='Algeria' sort_name='Algeria' sorttype='name' flag_class='icon_flag flag_DZ'><league name='阿尔及利亚甲组联赛' id='103231' t_sort='18001' grp='9' sort_name='Algeria Ligue 1'></league></region><region name='埃及' id='32' t_sort='Egypt' sort_name='Egypt' sorttype='name' flag_class='icon_flag flag_EG'><league name='埃及超级联赛' id='101322' t_sort='14010' grp='7' sort_name='Egypt Premier League'></league></region><region name='奇幻赛事' id='1374' t_sort='Fantasy Matches' sort_name='Fantasy Matches' sorttype='name' flag_class='icon_flag '><league name='奇幻赛事' id='108688' t_sort='50001' grp='9' sort_name='Fantasy Matches'></league></region><region name='以色列' id='52' t_sort='Israel' sort_name='Israel' sorttype='name' flag_class='icon_flag flag_IL'><league name='以色列超级联赛' id='102744' t_sort='15500' grp='9' sort_name='Israel Premier League'></league></region><region name='土耳其' id='109' t_sort='Turkey' sort_name='Turkey' sorttype='name' flag_class='icon_flag flag_TR'><league name='土耳其超级联赛' id='100123' t_sort='12020' grp='7' sort_name='Turkey Super League'></league><league name='土耳其甲组联赛' id='101743' t_sort='15100' grp='6' sort_name='Turkey TFF First League'></league></region><region name='阿联酋' id='9' t_sort='UAE' sort_name='UAE' sorttype='name' flag_class='icon_flag flag_AE'><league name='阿联酋超级联赛' id='101323' t_sort='15600' grp='4' sort_name='UAE Pro League'></league></region></classifier><classifier_debug></classifier_debug><coupon_debug></coupon_debug></serverresponse>";


$as = \zhqing\extend\Xml::xmlToArr($xml);
ps((object)$as);
ts(\zhqing\extend\Xml::arrToXml($as, ''));